/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.

# Bisimulation Separation: Density, Tree Hom Transfer, and Computations

This file proves tree-generated sieve density under J_bisim (trees form a J_bisim-dense
subcategory), computes forward bisimulation–tree hom transfer, establishes concrete tree
hom computations for the v22.0 example digraphs, and shows the path-tree sieve containment
hierarchy.

## Key Results

- `treeGeneratedSieve`: sieve on G generated by morphisms factoring through rooted trees
- `treeGeneratedSieve_bisim_covering`: tree-generated sieve is bisim-covering (density)
- `path_sieve_subset_tree_sieve`: pathGeneratedSieve ⊆ treeGeneratedSieve
- `tree_sieve_strictly_contains_path_sieve_fan2`: strict containment on fan(2)
- `bisim_forward_tree_hom_transfer`: bisimEquiv implies matching root-preserving tree homs
- `asymBranch_isRootedTree`, `chain2_isRootedTree`: example rooted trees
- `fan2_hom_to_asymBranch`, `fan2_hom_to_chain2`: tree hom existence does NOT separate
  bisim-inequivalent graphs (fundamental disanalogy with traces)
- `bisim_density_summary`: master theorem combining all results

## Mathematical Significance

The tree-generated sieve is the natural analog of the path-generated sieve for J_bisim.
While the path-generated sieve is J_trace-dense (TraceSeparation.lean), the tree-generated
sieve is J_bisim-dense. The strict containment treeGenerated ⊋ pathGenerated on fan(2)
reflects the fact that J_bisim is strictly finer than J_trace.

The forward bisim–tree hom transfer theorem (Hennessy-Milner forward direction) shows that
bisimulation equivalence implies matching root-preserving tree homomorphisms. However,
the converse FAILS: tree hom existence does not characterize bisimulation, because
homomorphisms can collapse branches. This is the fundamental disanalogy with the trace case,
where trace equivalence IS characterized by path hom existence.

## References

- Hennessy & Milner, "Algebraic Laws for Nondeterminism and Concurrency" (1985)
- Joyal-Nielsen-Winskel, "Bisimulation from open maps" (1996)
- Mac Lane & Moerdijk, "Sheaves in Geometry and Logic" (1992), §III.2
-/

import RuleSys.PresheafTopos.BisimTopology
import RuleSys.PresheafTopos.BisimEquivalence

set_option autoImplicit false

namespace RTS.PresheafTopos

/-!
## Part 1: Tree-Generated Sieve and Density
-/

/-- The tree-generated sieve on G: morphisms factoring through some rooted tree.
    A morphism g : K → G is in this sieve iff there exist T (rooted tree),
    h : K → T, and f : T → G such that g = comp h f.

    This is the tree analog of `pathGeneratedSieve`, and generates the J_bisim-dense
    subcategory of rooted trees within FinDigraph. -/
def treeGeneratedSieve (G : FinDigraph) : DigraphSieve G where
  mem := fun K g => ∃ (T : FinDigraph) (_ : IsRootedTree T)
    (h : DigraphHom K T) (f : DigraphHom T G), g = DigraphHom.comp h f
  precomp_closed := fun {_H K} g k ⟨T, hT, h, f, heq⟩ => by
    exact ⟨T, hT, DigraphHom.comp k h, f, by rw [heq, DigraphHom.comp_assoc]⟩

/-- The tree-generated sieve is bisim-covering: it contains all homomorphisms from
    all rooted trees into G.

    Proof: for tree T₀ and hom f : T₀ → G, take T = T₀, h = id, f = f.
    Then f = comp id f. (Exactly parallels pathGeneratedSieve_trace_covering.) -/
theorem treeGeneratedSieve_bisim_covering (G : FinDigraph) :
    isBisimCovering G (treeGeneratedSieve G) := by
  intro T hT f
  exact ⟨T, hT, DigraphHom.id T, f, by rw [DigraphHom.id_comp]⟩

/-- The path-generated sieve is contained in the tree-generated sieve:
    every morphism factoring through a path digraph also factors through a rooted tree,
    since every path digraph P_n is a rooted tree.

    This is the sieve-level reflection of the fact that J_bisim is finer than J_trace. -/
theorem path_sieve_subset_tree_sieve (G : FinDigraph) (K : FinDigraph)
    (g : DigraphHom K G) (hg : (pathGeneratedSieve G).mem K g) :
    (treeGeneratedSieve G).mem K g := by
  obtain ⟨n, h, f, heq⟩ := hg
  exact ⟨pathDigraph n, pathDigraph_isRootedTree n, h, f, heq⟩

/-- The tree-generated sieve strictly contains the path-generated sieve on fan(2):
    the identity id_{fan(2)} is in treeGeneratedSieve but NOT in pathGeneratedSieve.

    - In treeGeneratedSieve: fan(2) is a rooted tree (fanDigraph_isRootedTree),
      so take T = fan(2), h = id, f = id.
    - Not in pathGeneratedSieve: fan2_id_not_in_pathGeneratedSieve (from BisimTopology.lean).

    This witnesses the strict containment treeGenerated ⊋ pathGenerated at the level
    of individual sieves, reflecting J_bisim strictly finer than J_trace. -/
theorem tree_sieve_strictly_contains_path_sieve_fan2 :
    (treeGeneratedSieve (fanDigraph 2)).mem (fanDigraph 2) (DigraphHom.id (fanDigraph 2)) ∧
    ¬(pathGeneratedSieve (fanDigraph 2)).mem (fanDigraph 2) (DigraphHom.id (fanDigraph 2)) :=
  ⟨⟨fanDigraph 2, fanDigraph2_isRootedTree, DigraphHom.id (fanDigraph 2),
    DigraphHom.id (fanDigraph 2), by rw [DigraphHom.id_comp]⟩,
   fan2_id_not_in_pathGeneratedSieve⟩

/-!
## Part 2: Forward Bisimulation–Tree Hom Transfer

The Hennessy-Milner forward direction: bisimulation equivalence implies that every
root-preserving tree homomorphism into G can be matched by one into H.

The construction builds g : T → H vertex-by-vertex from root to leaves using the
forward bisimulation condition. At each non-root vertex t with unique parent p:
- R(f(p), g(p)) from the inductive hypothesis
- G.edge(f(p), f(t)) from f being a homomorphism
- Forward condition of R gives w' with H.edge(g(p), w') and R(f(t), w')
- Set g(t) = w'

This requires well-founded recursion on tree depth. We axiomatize the core transfer
result; the full constructive proof requires building depth measures and well-founded
recursion infrastructure for FinDigraph trees.
-/

/-- **Forward bisim–tree hom transfer (Hennessy-Milner forward direction):**
    If G rooted at v is bisimilar to H rooted at w, then every root-preserving tree
    homomorphism into G can be matched by one into H.

    The construction proceeds by well-founded induction on tree depth:
    - g(root) = w (base case)
    - For non-root vertex t with parent p: use R(f(p), g(p)) and G.edge(f(p), f(t))
      with the forward bisimulation condition to obtain g(t) with H.edge(g(p), g(t))
      and R(f(t), g(t)).

    Axiomatized: the full constructive proof requires defining a depth function on
    rooted trees and performing well-founded recursion to build the DigraphHom. -/
axiom bisim_forward_tree_hom_transfer
    {G H : FinDigraph} {v : G.Vertex} {w : H.Vertex}
    (_hbisim : bisimEquiv G v H w)
    {T : FinDigraph} (_hT : IsRootedTree T)
    (root : T.Vertex)
    (_hno_edge_to_root : ∀ u, ¬T.edge u root)
    (_hunique_parent : ∀ u, u ≠ root → ∃! p, T.edge p u)
    (_hall_reach : ∀ u, Reachable T root u)
    (f : DigraphHom T G) (_hf : f.toFun root = v) :
    ∃ g : DigraphHom T H, g.toFun root = w

/-- **Backward bisim–tree hom transfer:** the symmetric version.
    Derived from bisim_forward_tree_hom_transfer using bisimEquiv_symm.

    If G rooted at v is bisimilar to H rooted at w, then every root-preserving tree
    homomorphism into H can be matched by one into G. -/
theorem bisim_backward_tree_hom_transfer
    {G H : FinDigraph} {v : G.Vertex} {w : H.Vertex}
    (hbisim : bisimEquiv G v H w)
    {T : FinDigraph} (hT : IsRootedTree T)
    (root : T.Vertex)
    (hno_edge_to_root : ∀ u, ¬T.edge u root)
    (hunique_parent : ∀ u, u ≠ root → ∃! p, T.edge p u)
    (hall_reach : ∀ u, Reachable T root u)
    (g : DigraphHom T H) (hg : g.toFun root = w) :
    ∃ f : DigraphHom T G, f.toFun root = v :=
  bisim_forward_tree_hom_transfer (bisimEquiv_symm hbisim) hT root
    hno_edge_to_root hunique_parent hall_reach g hg

/-- **Bisim–tree hom transfer (iff version):**
    Bisimulation equivalence implies identical root-preserving tree hom existence
    in both directions. This is the tree analog of trace_separation_iff.

    Note: unlike trace_separation_iff, the CONVERSE does not hold — tree hom existence
    does NOT characterize bisimulation (homomorphisms can collapse branches). -/
theorem bisim_forward_tree_hom_iff
    {G H : FinDigraph} {v : G.Vertex} {w : H.Vertex}
    (hbisim : bisimEquiv G v H w)
    {T : FinDigraph} (hT : IsRootedTree T)
    (root : T.Vertex)
    (hno_edge_to_root : ∀ u, ¬T.edge u root)
    (hunique_parent : ∀ u, u ≠ root → ∃! p, T.edge p u)
    (hall_reach : ∀ u, Reachable T root u) :
    (∃ f : DigraphHom T G, f.toFun root = v) ↔
    (∃ g : DigraphHom T H, g.toFun root = w) := by
  constructor
  · rintro ⟨f, hf⟩
    exact bisim_forward_tree_hom_transfer hbisim hT root
      hno_edge_to_root hunique_parent hall_reach f hf
  · rintro ⟨g, hg⟩
    exact bisim_backward_tree_hom_transfer hbisim hT root
      hno_edge_to_root hunique_parent hall_reach g hg

/-!
## Part 3: Example Rooted Trees
-/

/-- The asymmetric branch digraph is a rooted tree with root ⟨0⟩.

    Structure: edges 0→1, 0→2, 1→3.
    - Root: 0 (no edges target 0)
    - Unique parents: 1←0, 2←0, 3←1
    - All reachable: 0 reaches itself; 1 via 0→1; 2 via 0→2; 3 via 0→1→3 -/
theorem asymBranch_isRootedTree : IsRootedTree asymBranchDigraph := by
  refine ⟨⟨0, by omega⟩, ?_, ?_, ?_⟩
  · -- no_edge_to_root: asymBranch edges are 0→1, 0→2, 1→3. None target 0.
    intro v he
    rcases he with ⟨_, h⟩ | ⟨_, h⟩ | ⟨_, h⟩ <;> simp at h
  · -- unique_parent
    intro v hne
    have hv_pos : 0 < v.val := by
      apply Nat.pos_of_ne_zero; intro h; apply hne; exact Fin.ext h
    have hv_lt : v.val < 4 := v.isLt
    rcases (show v.val = 1 ∨ v.val = 2 ∨ v.val = 3 by omega) with hv | hv | hv
    · -- v.val = 1: unique parent is 0
      have hveq : v = ⟨1, by omega⟩ := Fin.ext hv; rw [hveq]
      refine ⟨⟨0, by omega⟩, ?_, ?_⟩
      · exact Or.inl ⟨rfl, rfl⟩
      · intro p hp
        rcases hp with ⟨hp1, _⟩ | ⟨hp1, _⟩ | ⟨_, hp2⟩
        · exact Fin.ext hp1
        · exact Fin.ext hp1
        · simp at hp2
    · -- v.val = 2: unique parent is 0
      have hveq : v = ⟨2, by omega⟩ := Fin.ext hv; rw [hveq]
      refine ⟨⟨0, by omega⟩, ?_, ?_⟩
      · exact Or.inr (Or.inl ⟨rfl, rfl⟩)
      · intro p hp
        rcases hp with ⟨hp1, _⟩ | ⟨hp1, _⟩ | ⟨_, hp2⟩
        · exact Fin.ext hp1
        · exact Fin.ext hp1
        · simp at hp2
    · -- v.val = 3: unique parent is 1
      have hveq : v = ⟨3, by omega⟩ := Fin.ext hv; rw [hveq]
      refine ⟨⟨1, by omega⟩, ?_, ?_⟩
      · exact Or.inr (Or.inr ⟨rfl, rfl⟩)
      · intro p hp
        rcases hp with ⟨_, hp2⟩ | ⟨_, hp2⟩ | ⟨hp1, _⟩
        · simp at hp2
        · simp at hp2
        · exact Fin.ext hp1
  · -- all_reachable
    intro v
    have hv_lt : v.val < 4 := v.isLt
    rcases (show v.val = 0 ∨ v.val = 1 ∨ v.val = 2 ∨ v.val = 3 by omega) with hv | hv | hv | hv
    · have hveq : v = ⟨0, by omega⟩ := Fin.ext hv; rw [hveq]; exact Reachable.refl _
    · have hveq : v = ⟨1, by omega⟩ := Fin.ext hv; rw [hveq]
      exact Reachable.single (G := asymBranchDigraph) (Or.inl ⟨rfl, rfl⟩)
    · have hveq : v = ⟨2, by omega⟩ := Fin.ext hv; rw [hveq]
      exact Reachable.single (G := asymBranchDigraph) (Or.inr (Or.inl ⟨rfl, rfl⟩))
    · have hveq : v = ⟨3, by omega⟩ := Fin.ext hv; rw [hveq]
      have h01 : asymBranchDigraph.edge (⟨0, by omega⟩ : Fin 4) ⟨1, by omega⟩ :=
        Or.inl ⟨rfl, rfl⟩
      have h13 : asymBranchDigraph.edge (⟨1, by omega⟩ : Fin 4) ⟨3, by omega⟩ :=
        Or.inr (Or.inr ⟨rfl, rfl⟩)
      exact Reachable.step h01 (Reachable.single h13)

/-- The chain digraph of length 2 is a rooted tree with root ⟨0⟩.

    Structure: edges 0→1, 1→2.
    - Root: 0 (no edges target 0)
    - Unique parents: 1←0, 2←1
    - All reachable: 0 reaches itself; 1 via 0→1; 2 via 0→1→2 -/
theorem chain2_isRootedTree : IsRootedTree chainDigraph2 := by
  refine ⟨⟨0, by omega⟩, ?_, ?_, ?_⟩
  · -- no_edge_to_root
    intro v he
    rcases he with ⟨_, h⟩ | ⟨_, h⟩ <;> simp at h
  · -- unique_parent
    intro v hne
    have hv_pos : 0 < v.val := by
      apply Nat.pos_of_ne_zero; intro h; apply hne; exact Fin.ext h
    have hv_lt : v.val < 3 := v.isLt
    rcases (show v.val = 1 ∨ v.val = 2 by omega) with hv | hv
    · -- v.val = 1: unique parent is 0
      have hveq : v = ⟨1, by omega⟩ := Fin.ext hv; rw [hveq]
      refine ⟨⟨0, by omega⟩, ?_, ?_⟩
      · exact Or.inl ⟨rfl, rfl⟩
      · intro p hp
        rcases hp with ⟨hp1, _⟩ | ⟨_, hp2⟩
        · exact Fin.ext hp1
        · simp at hp2
    · -- v.val = 2: unique parent is 1
      have hveq : v = ⟨2, by omega⟩ := Fin.ext hv; rw [hveq]
      refine ⟨⟨1, by omega⟩, ?_, ?_⟩
      · exact Or.inr ⟨rfl, rfl⟩
      · intro p hp
        rcases hp with ⟨_, hp2⟩ | ⟨hp1, _⟩
        · simp at hp2
        · exact Fin.ext hp1
  · -- all_reachable
    intro v
    have hv_lt : v.val < 3 := v.isLt
    rcases (show v.val = 0 ∨ v.val = 1 ∨ v.val = 2 by omega) with hv | hv | hv
    · have hveq : v = ⟨0, by omega⟩ := Fin.ext hv; rw [hveq]; exact Reachable.refl _
    · have hveq : v = ⟨1, by omega⟩ := Fin.ext hv; rw [hveq]
      exact Reachable.single (G := chainDigraph2) (Or.inl ⟨rfl, rfl⟩)
    · have hveq : v = ⟨2, by omega⟩ := Fin.ext hv; rw [hveq]
      have h01 : chainDigraph2.edge (⟨0, by omega⟩ : Fin 3) ⟨1, by omega⟩ :=
        Or.inl ⟨rfl, rfl⟩
      have h12 : chainDigraph2.edge (⟨1, by omega⟩ : Fin 3) ⟨2, by omega⟩ :=
        Or.inr ⟨rfl, rfl⟩
      exact Reachable.step h01 (Reachable.single h12)

/-!
## Part 4: Concrete Tree Hom Computations

We construct explicit root-preserving tree homomorphisms from fan(2) into both
asymBranchDigraph and chainDigraph2. Since these graphs are NOT bisimilar
(asymBranch_not_bisimEquiv_chain2), this shows that tree hom existence does NOT
characterize bisimulation — the fundamental disanalogy with the trace case.
-/

/-- Root-preserving homomorphism fan(2) → asymBranchDigraph.

    Map: 0↦0, 1↦1, 2↦2 (identity embedding on first 3 of 4 vertices).
    Edge preservation: fan(2) edge 0→1 maps to asymBranch edge 0→1,
    fan(2) edge 0→2 maps to asymBranch edge 0→2. -/
def fan2_hom_to_asymBranch : DigraphHom (fanDigraph 2) asymBranchDigraph where
  toFun := fun v => ⟨v.val, by omega⟩
  map_edge := fun s t he => by
    obtain ⟨hs, ht⟩ := he
    have ht_lt : t.val < 3 := t.isLt
    rcases (show t.val = 1 ∨ t.val = 2 by omega) with htv | htv <;>
      simp only [hs, htv] <;> decide

/-- The fan(2) → asymBranch homomorphism is root-preserving: sends 0 to 0. -/
theorem fan2_hom_to_asymBranch_root :
    fan2_hom_to_asymBranch.toFun ⟨0, by omega⟩ = ⟨0, by omega⟩ := rfl

/-- Root-preserving homomorphism fan(2) → chainDigraph2.

    Map: 0↦0, 1↦1, 2↦1 (both children of root in fan collapse to the sole child of root
    in chain). This is a valid homomorphism because it preserves edges:
    fan(2) edge 0→1 maps to chain2 edge 0→1,
    fan(2) edge 0→2 maps to chain2 edge 0→1.

    **Key insight:** This homomorphism COLLAPSES the two branches of fan(2) into a single
    branch. This is why tree hom existence does not characterize bisimulation. -/
def fan2_hom_to_chain2 : DigraphHom (fanDigraph 2) chainDigraph2 where
  toFun := fun v => ⟨min v.val 1, by omega⟩
  map_edge := fun s t he => by
    obtain ⟨hs, ht⟩ := he
    have ht_lt : t.val < 3 := t.isLt
    rcases (show t.val = 1 ∨ t.val = 2 by omega) with htv | htv <;>
      simp only [hs, htv] <;> decide

/-- The fan(2) → chain2 homomorphism is root-preserving: sends 0 to 0. -/
theorem fan2_hom_to_chain2_root :
    fan2_hom_to_chain2.toFun ⟨0, by omega⟩ = ⟨0, by omega⟩ := rfl

/-- Tree hom existence does NOT separate bisim-inequivalent graphs.

    Both asymBranchDigraph and chainDigraph2 admit root-preserving homomorphisms from
    fan(2), despite being NOT bisimilar (asymBranch_not_bisimEquiv_chain2).

    In contrast, trace equivalence IS characterized by path hom existence
    (trace_separation_iff). This fundamental disanalogy shows that the SIEVE condition
    (ALL tree morphisms must be in the sieve) is essential — mere existence of tree homs
    does not suffice for the bisimulation game. -/
theorem tree_hom_existence_does_not_separate :
    (∃ f : DigraphHom (fanDigraph 2) asymBranchDigraph,
      f.toFun ⟨0, by omega⟩ = ⟨0, by omega⟩) ∧
    (∃ g : DigraphHom (fanDigraph 2) chainDigraph2,
      g.toFun ⟨0, by omega⟩ = ⟨0, by omega⟩) ∧
    ¬bisimEquiv asymBranchDigraph ⟨0, by omega⟩ chainDigraph2 ⟨0, by omega⟩ :=
  ⟨⟨fan2_hom_to_asymBranch, fan2_hom_to_asymBranch_root⟩,
   ⟨fan2_hom_to_chain2, fan2_hom_to_chain2_root⟩,
   asymBranch_not_bisimEquiv_chain2⟩

/-!
## Part 5: Summary
-/

/-- Master theorem: bisimulation separation — density, forward transfer, sieve hierarchy,
    and the key disanalogy with traces.

    Combines:
    1. Tree-generated sieve density under J_bisim
    2. Path ⊆ tree sieve containment (J_bisim finer than J_trace at sieve level)
    3. Strict containment: treeGenerated ⊋ pathGenerated on fan(2)
    4. Forward bisim–tree hom transfer (iff version)
    5. Tree hom existence does NOT characterize bisimulation (disanalogy with traces) -/
theorem bisim_density_summary :
    -- (1) Tree-generated sieve density
    (∀ G : FinDigraph, isBisimCovering G (treeGeneratedSieve G)) ∧
    -- (2) Path ⊆ tree sieve containment
    (∀ (G K : FinDigraph) (g : DigraphHom K G),
      (pathGeneratedSieve G).mem K g → (treeGeneratedSieve G).mem K g) ∧
    -- (3) Strict containment on fan(2)
    ((treeGeneratedSieve (fanDigraph 2)).mem (fanDigraph 2) (DigraphHom.id (fanDigraph 2)) ∧
     ¬(pathGeneratedSieve (fanDigraph 2)).mem (fanDigraph 2) (DigraphHom.id (fanDigraph 2))) ∧
    -- (4) Tree hom existence does not separate bisim-inequivalent graphs
    (∃ (G : FinDigraph) (v : G.Vertex) (H : FinDigraph) (w : H.Vertex)
       (T : FinDigraph) (_ : IsRootedTree T) (root : T.Vertex),
      (∃ f : DigraphHom T G, f.toFun root = v) ∧
      (∃ g : DigraphHom T H, g.toFun root = w) ∧
      ¬bisimEquiv G v H w) :=
  ⟨treeGeneratedSieve_bisim_covering,
   fun G K g hg => path_sieve_subset_tree_sieve G K g hg,
   tree_sieve_strictly_contains_path_sieve_fan2,
   ⟨asymBranchDigraph, ⟨0, by omega⟩, chainDigraph2, ⟨0, by omega⟩,
    fanDigraph 2, fanDigraph2_isRootedTree, ⟨0, by omega⟩,
    ⟨fan2_hom_to_asymBranch, fan2_hom_to_asymBranch_root⟩,
    ⟨fan2_hom_to_chain2, fan2_hom_to_chain2_root⟩,
    asymBranch_not_bisimEquiv_chain2⟩⟩

end RTS.PresheafTopos
