/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.

# Labeled Bisimulation Topology, Bracket Theorem, and Strict Separation

This file defines the labeled bisimulation Grothendieck topology J_bisim on the category
of finite L-labeled transition systems. It includes:
- Labeled bisimulation definition and bisimulation equivalence
- Non-bisimilarity proof for van Glabbeek's a.b+a.c vs a.(b+c) counterexample
- traceLTS as labeled rooted tree
- Bisim-covering predicate with three Grothendieck axioms
- Labeled tree-generated sieve and density
- Labeled observation class framework with bracket theorem
- Strict separation: J_bisim strictly finer than J_trace

## Key Results

- `LabeledBisimulation`: forward + backward zig-zag for each label
- `labeledBisimEquiv`: existence of labeled bisimulation relating roots
- `vgPairA_not_bisim_vgPairB`: a.b+a.c NOT bisimilar to a.(b+c)
- `traceLTS_isLabeledRootedTree`: trace path LTS is a labeled rooted tree
- `isLabeledBisimCovering`: covering predicate for J_bisim
- Three Grothendieck axioms for J_bisim
- `labeledBisimCovering_implies_trace_covering`: J_bisim finer than J_trace
- `labeledTreeGeneratedSieve`: sieve generated by tree factorizations
- `LabeledObservationClass`: parametric observation class framework
- `labeled_spectrum_bracket_upper/lower`: J_bisim <= J_C <= J_trace
- `labeled_bisim_strictly_finer_than_trace`: strict separation via fanLTS

## Mathematical Significance

This is the labeled generalization of v22.0 Phases 169-172. The bisimulation topology
uses labeled rooted trees as test objects (probes). Together with J_trace (Phase 175),
it brackets the labeled van Glabbeek spectrum: J_bisim <= J_C <= J_trace for observation
classes C between paths and trees. The strict separation uses the fan LTS (root with two
differently-labeled children) as witness: its identity does not factor through any traceLTS.

## References

- Mac Lane & Moerdijk, "Sheaves in Geometry and Logic" (1992), III.2
- van Glabbeek, "The linear time--branching time spectrum I" (1990)
- Joyal-Nielsen-Winskel, "Bisimulation from open maps" (1996)
-/

import RuleSys.PresheafTopos.LabeledTraceTopology

set_option autoImplicit false

namespace RTS.PresheafTopos

/-!
## Part 1: Labeled Bisimulation Definition
-/

/-- A labeled bisimulation between G and H is a relation R such that:
    - Forward: if R s t and G.edge a s s', then exists t' with H.edge a t t' and R s' t'
    - Backward: if R s t and H.edge a t t', then exists s' with G.edge a s s' and R s' t' -/
def LabeledBisimulation {L : Type} [Fintype L] [DecidableEq L]
    (G H : FinLTS L) (R : G.Vertex → H.Vertex → Prop) : Prop :=
  (∀ s t, R s t → ∀ (a : L) s', G.edge a s s' → ∃ t', H.edge a t t' ∧ R s' t') ∧
  (∀ s t, R s t → ∀ (a : L) t', H.edge a t t' → ∃ s', G.edge a s s' ∧ R s' t')

/-- Two rooted labeled LTS are bisimulation-equivalent if there exists a
    labeled bisimulation R relating their roots. -/
def labeledBisimEquiv {L : Type} [Fintype L] [DecidableEq L]
    (G : FinLTS L) (v : G.Vertex) (H : FinLTS L) (w : H.Vertex) : Prop :=
  ∃ R : G.Vertex → H.Vertex → Prop, R v w ∧ LabeledBisimulation G H R

/-!
## Part 2: Van Glabbeek Non-Bisimilarity Proof

vgPairA = a.b + a.c (5 vertices: s0 -a-> s1 -b-> s3, s0 -a-> s2 -c-> s4)
vgPairB = a.(b+c)   (3 vertices: s0 -a-> s1 -b-> s2, s1 -c-> s2)

These are trace-equivalent but NOT bisimilar. The key insight: in vgPairA,
the two a-successors of s0 have disjoint continuation capabilities
(s1 can only do b, s2 can only do c), but in vgPairB, the single
a-successor s1 can do both b and c.
-/

/-- Helper: in vgPairA, vertex 1 has no c-edge.
    We use native_decide since the DecidableRel instances use tactics. -/
private theorem vgPairA_no_c_from_1 (w : vgPairA.Vertex) :
    ¬vgPairA.edge ThreeLabel.c ⟨1, by omega⟩ w := by
  revert w
  native_decide

/-- Helper: in vgPairA, vertex 2 has no b-edge. -/
private theorem vgPairA_no_b_from_2 (w : vgPairA.Vertex) :
    ¬vgPairA.edge ThreeLabel.b ⟨2, by omega⟩ w := by
  revert w
  native_decide

/-- Helper: in vgPairB, the only a-successor of vertex 0 is vertex 1. -/
private theorem vgPairB_a_unique (t : vgPairB.Vertex)
    (h : vgPairB.edge ThreeLabel.a ⟨0, by omega⟩ t) : t = ⟨1, by omega⟩ := by
  revert t
  native_decide

/-- Helper: vgPairB has a c-edge from vertex 1 to vertex 2. -/
private theorem vgPairB_has_c :
    vgPairB.edge ThreeLabel.c ⟨1, by omega⟩ ⟨2, by omega⟩ := by
  native_decide

/-- Helper: vgPairB has a b-edge from vertex 1 to vertex 2. -/
private theorem vgPairB_has_b :
    vgPairB.edge ThreeLabel.b ⟨1, by omega⟩ ⟨2, by omega⟩ := by
  native_decide

/-- vgPairA (a.b+a.c) and vgPairB (a.(b+c)) are NOT bisimilar.

    Proof: assume R is a labeled bisimulation with R s0_A s0_B.
    Forward with label 'a': vgPairA has edge a from s0 to s1.
    In vgPairB, the only a-successor of s0 is s1. So R s1_A s1_B.
    Backward c from s1_B: vgPairB has c-edge from s1 to s2.
    Need c-edge from s1_A in vgPairA, but vertex 1 has no c-edge. Contradiction. -/
theorem vgPairA_not_bisim_vgPairB :
    ¬labeledBisimEquiv vgPairA (show vgPairA.Vertex from ⟨0, by omega⟩)
                        vgPairB (show vgPairB.Vertex from ⟨0, by omega⟩) := by
  intro ⟨R, hR_root, hfwd, hbwd⟩
  -- vgPairA has a-edge from 0 to 1
  have hedge_a01 : vgPairA.edge ThreeLabel.a ⟨0, by omega⟩ ⟨1, by omega⟩ := by native_decide
  -- Forward: R s0_A s0_B and edge a s0_A s1_A → ∃ t', B.edge a s0_B t' ∧ R s1_A t'
  obtain ⟨t', ht'_edge, hR_1t'⟩ := hfwd _ _ hR_root ThreeLabel.a _ hedge_a01
  -- t' must be ⟨1,_⟩ in vgPairB (unique a-successor)
  have ht'_eq := vgPairB_a_unique t' ht'_edge
  -- Backward: R s1_A t' and B.edge c t' ⟨2,_⟩ → ∃ s', A.edge c s1_A s'
  rw [ht'_eq] at hR_1t'
  obtain ⟨s'_c, hs'_c_edge, _⟩ := hbwd _ _ hR_1t' ThreeLabel.c ⟨2, by omega⟩ vgPairB_has_c
  exact vgPairA_no_c_from_1 s'_c hs'_c_edge

/-!
## Part 3: traceLTS is a Labeled Rooted Tree
-/

/-- Helper: in traceLTS w, vertex 0 can reach any vertex by induction on value. -/
private theorem traceLTS_reachable_aux {L : Type} [Fintype L] [DecidableEq L]
    (w : List L) (m : ℕ) (hm : m ≤ w.length) :
    LabeledReachable (traceLTS w) ⟨0, Nat.zero_lt_succ w.length⟩ ⟨m, by omega⟩ := by
  induction m with
  | zero => exact LabeledReachable.refl _
  | succ k ih =>
    have hreach := ih (by omega)
    have hk_lt : k < w.length := by omega
    have hk1_lt : k + 1 < w.length + 1 := by omega
    have hedge : (traceLTS w).edge (w.get ⟨k, hk_lt⟩)
        (⟨k, by omega⟩ : Fin (w.length + 1))
        (⟨k + 1, hk1_lt⟩ : Fin (w.length + 1)) := by
      refine ⟨hk_lt, ?_, ?_⟩
      · rfl
      · rfl
    exact hreach.trans (LabeledReachable.step (w.get ⟨k, hk_lt⟩) hedge (LabeledReachable.refl _))

/-- Every traceLTS w is a labeled rooted tree with root ⟨0⟩.

    - No edge to root: traceLTS edge requires t.val = s.val + 1 >= 1, so t cannot be 0.
    - Unique parent: for v with v.val > 0, parent is ⟨v.val - 1⟩ with label w[v.val - 1].
    - All reachable: by induction on v.val. -/
theorem traceLTS_isLabeledRootedTree {L : Type} [Fintype L] [DecidableEq L]
    (w : List L) : LabeledIsRootedTree (traceLTS w) := by
  refine ⟨⟨0, Nat.zero_lt_succ w.length⟩, ?_, ?_, ?_⟩
  · -- no_edge_to_root: no labeled edge targets vertex 0
    intro a v he
    obtain ⟨_, _, hj⟩ := he
    -- hj : (0 : Fin _).val = v.val + 1
    simp at hj
  · -- unique_parent: for v ≠ root, unique p with ∃ a, edge a p v
    intro v hne
    have hv_pos : 0 < v.val := by
      by_contra h
      push_neg at h
      apply hne
      apply Fin.ext
      show v.val = 0
      omega
    refine ⟨⟨v.val - 1, by omega⟩, ?_, ?_⟩
    · -- Existence: edge from ⟨v.val - 1⟩ to v with label w[v.val - 1]
      refine ⟨w.get ⟨v.val - 1, by omega⟩, ?_⟩
      have hvm1_lt : v.val - 1 < w.length := by omega
      refine ⟨hvm1_lt, ?_, ?_⟩
      · -- w.get ⟨(v.val - 1), hvm1_lt⟩ = w.get ⟨v.val - 1, by omega⟩
        rfl
      · -- v.val = (v.val - 1) + 1
        show v.val = (⟨v.val - 1, _⟩ : Fin (w.length + 1)).val + 1
        simp; omega
    · -- Uniqueness: any parent p must equal ⟨v.val - 1⟩
      intro p ⟨_, _, _, hj⟩
      -- hj : v.val = p.val + 1
      apply Fin.ext
      show p.val = v.val - 1
      omega
  · -- all_reachable
    intro v
    have := traceLTS_reachable_aux w v.val (by omega)
    have hv_eq : v = ⟨v.val, v.isLt⟩ := rfl
    rw [hv_eq]
    exact this

/-!
## Part 4: Labeled Bisim-Covering Predicate
-/

/-- A sieve S on G is **labeled-bisim-covering** if it contains every homomorphism from
    every labeled rooted tree T into G. This is the covering condition for J_bisim.

    Compared to isLabeledTraceCovering (which only requires traceLTS morphisms), this is
    strictly stronger: it requires all tree-shaped probes, not just linear ones. -/
def isLabeledBisimCovering {L : Type} [Fintype L] [DecidableEq L]
    (G : FinLTS L) (S : LTSSieve G) : Prop :=
  ∀ (T : FinLTS L), LabeledIsRootedTree T → ∀ (f : LTSHom T G), S.mem T f

/-- Every bisim-covering sieve is trace-covering: since every traceLTS w is a labeled
    rooted tree, requiring all tree morphisms subsumes requiring all trace morphisms.

    This is the inclusion J_bisim <= J_trace as Grothendieck topologies. -/
theorem labeledBisimCovering_implies_trace_covering
    {L : Type} [Fintype L] [DecidableEq L]
    {G : FinLTS L} {S : LTSSieve G}
    (hS : isLabeledBisimCovering G S) : isLabeledTraceCovering G S :=
  fun w f => hS (traceLTS w) (traceLTS_isLabeledRootedTree w) f

/-!
## Part 5: Three Grothendieck Axioms for Labeled J_bisim
-/

/-- **Maximality axiom:** The maximal sieve is bisim-covering for every G. -/
theorem labeled_bisim_covering_maximal {L : Type} [Fintype L] [DecidableEq L]
    (G : FinLTS L) :
    isLabeledBisimCovering G (LTSSieve.maximal G) :=
  fun _ _ _ => trivial

/-- **Stability axiom:** If S bisim-covers G, then the pullback h*(S) bisim-covers H.
    Any tree morphism f : T -> H becomes h . f : T -> G, which is in S. -/
theorem labeled_bisim_covering_stable {L : Type} [Fintype L] [DecidableEq L]
    {G H : FinLTS L} {S : LTSSieve G}
    (h : LTSHom H G) (hS : isLabeledBisimCovering G S) :
    isLabeledBisimCovering H (S.pullback h) :=
  fun T hT f => hS T hT (LTSHom.comp f h)

/-- **Transitivity axiom:** If S bisim-covers G and for every (H, f) in S the pullback
    f*(T) bisim-covers H, then T bisim-covers G.

    Key insight (self-probing trick): for any tree T_0 and g : T_0 -> G, g in S
    (since S bisim-covers). Then T.pullback g bisim-covers T_0. Since T_0 is a tree,
    id_{T_0} in T.pullback g, giving g . id = g in T. -/
theorem labeled_bisim_covering_transitive {L : Type} [Fintype L] [DecidableEq L]
    {G : FinLTS L} {S T : LTSSieve G}
    (hS : isLabeledBisimCovering G S)
    (hT : ∀ (H : FinLTS L) (f : LTSHom H G), S.mem H f →
      isLabeledBisimCovering H (T.pullback f)) :
    isLabeledBisimCovering G T := by
  intro T₀ hT₀ g
  have hg : S.mem T₀ g := hS T₀ hT₀ g
  have hTg : isLabeledBisimCovering T₀ (T.pullback g) := hT T₀ g hg
  have hid := hTg T₀ hT₀ (LTSHom.id T₀)
  simp only [LTSSieve.pullback] at hid
  rw [LTSHom.id_comp] at hid
  exact hid

/-!
## Part 6: Labeled Bisim Topology Summary
-/

/-- Master theorem: J_bisim is a Grothendieck topology, finer than J_trace. -/
theorem labeled_bisim_topology_summary {L : Type} [Fintype L] [DecidableEq L] :
    -- (1) Maximality
    (∀ G : FinLTS L, isLabeledBisimCovering G (LTSSieve.maximal G)) ∧
    -- (2) Stability
    (∀ (G H : FinLTS L) (S : LTSSieve G) (h : LTSHom H G),
      isLabeledBisimCovering G S → isLabeledBisimCovering H (S.pullback h)) ∧
    -- (3) Transitivity
    (∀ (G : FinLTS L) (S T : LTSSieve G),
      isLabeledBisimCovering G S →
      (∀ (H : FinLTS L) (f : LTSHom H G), S.mem H f →
        isLabeledBisimCovering H (T.pullback f)) →
      isLabeledBisimCovering G T) ∧
    -- (4) J_bisim implies J_trace
    (∀ (G : FinLTS L) (S : LTSSieve G),
      isLabeledBisimCovering G S → isLabeledTraceCovering G S) :=
  ⟨labeled_bisim_covering_maximal,
   fun _ _ _ h hS => labeled_bisim_covering_stable h hS,
   fun _ _ _ hS hT => labeled_bisim_covering_transitive hS hT,
   fun _ _ hS => labeledBisimCovering_implies_trace_covering hS⟩

/-!
## Part 7: Labeled Tree-Generated Sieve
-/

/-- The tree-generated sieve on G: morphisms factoring through some labeled rooted tree.
    A morphism g : K -> G is in this sieve iff there exist T (labeled rooted tree),
    h : K -> T, and f : T -> G such that g = comp h f. -/
def labeledTreeGeneratedSieve {L : Type} [Fintype L] [DecidableEq L]
    (G : FinLTS L) : LTSSieve G where
  mem := fun K g => ∃ (T : FinLTS L) (_ : LabeledIsRootedTree T)
    (h : LTSHom K T) (f : LTSHom T G), g = LTSHom.comp h f
  precomp_closed := fun {_H K} g k ⟨T, hT, h, f, heq⟩ => by
    exact ⟨T, hT, LTSHom.comp k h, f, by rw [heq, LTSHom.comp_assoc]⟩

/-- The tree-generated sieve is bisim-covering: for tree T_0 and f : T_0 -> G,
    take T = T_0, h = id, f = f. -/
theorem labeledTreeGeneratedSieve_bisim_covering {L : Type} [Fintype L] [DecidableEq L]
    (G : FinLTS L) :
    isLabeledBisimCovering G (labeledTreeGeneratedSieve G) := by
  intro T hT f
  exact ⟨T, hT, LTSHom.id T, f, by rw [LTSHom.id_comp]⟩

/-- Trace-generated sieve is contained in tree-generated sieve: every morphism factoring
    through traceLTS w also factors through a labeled rooted tree. -/
theorem labeled_trace_sieve_subset_tree_sieve {L : Type} [Fintype L] [DecidableEq L]
    (G : FinLTS L) (K : FinLTS L)
    (g : LTSHom K G) (hg : (traceGeneratedSieve G).mem K g) :
    (labeledTreeGeneratedSieve G).mem K g := by
  obtain ⟨w, h, f, heq⟩ := hg
  exact ⟨traceLTS w, traceLTS_isLabeledRootedTree w, h, f, heq⟩

/-!
## Part 8: Labeled Observation Class Framework
-/

/-- An observation class for L-labeled LTS: a predicate specifying which LTS serve as
    test objects for the covering condition. -/
def LabeledObservationClass (L : Type) [Fintype L] [DecidableEq L] :=
  FinLTS L → Prop

/-- A sieve S on G is **C-covering** if it contains every homomorphism from every
    test object T in C into G. -/
def isLabeledObsCovering {L : Type} [Fintype L] [DecidableEq L]
    (C : LabeledObservationClass L) (G : FinLTS L) (S : LTSSieve G) : Prop :=
  ∀ (T : FinLTS L), C T → ∀ (f : LTSHom T G), S.mem T f

/-- The labeled path observation class: T is a test object iff T = traceLTS w for some w. -/
def labeledPathClass {L : Type} [Fintype L] [DecidableEq L] :
    LabeledObservationClass L :=
  fun T => ∃ w : List L, T = traceLTS w

/-- The labeled tree observation class: T is a test object iff T is a labeled rooted tree. -/
def labeledTreeClass {L : Type} [Fintype L] [DecidableEq L] :
    LabeledObservationClass L :=
  fun T => LabeledIsRootedTree T

/-- Monotonicity: larger observation class gives finer topology.
    C1 <= C2 implies C2-covering implies C1-covering. -/
theorem labeled_obs_covering_monotone {L : Type} [Fintype L] [DecidableEq L]
    {C₁ C₂ : LabeledObservationClass L}
    (h : ∀ T, C₁ T → C₂ T) {G : FinLTS L} {S : LTSSieve G}
    (hS : isLabeledObsCovering C₂ G S) : isLabeledObsCovering C₁ G S :=
  fun T hT f => hS T (h T hT) f

/-- Every labeled path class object is a labeled tree: traceLTS w is a rooted tree. -/
theorem labeled_pathClass_subset_treeClass {L : Type} [Fintype L] [DecidableEq L]
    (T : FinLTS L) (hT : labeledPathClass T) : labeledTreeClass T := by
  obtain ⟨w, rfl⟩ := hT
  exact traceLTS_isLabeledRootedTree w

/-!
## Part 9: Grothendieck Axioms for Observation-Class Topologies
-/

/-- **Maximality axiom** for observation-class covering. -/
theorem labeled_obs_covering_maximal {L : Type} [Fintype L] [DecidableEq L]
    (C : LabeledObservationClass L) (G : FinLTS L) :
    isLabeledObsCovering C G (LTSSieve.maximal G) :=
  fun _ _ _ => trivial

/-- **Stability axiom** for observation-class covering. -/
theorem labeled_obs_covering_stable {L : Type} [Fintype L] [DecidableEq L]
    {C : LabeledObservationClass L} {G H : FinLTS L} {S : LTSSieve G}
    (h : LTSHom H G) (hS : isLabeledObsCovering C G S) :
    isLabeledObsCovering C H (S.pullback h) :=
  fun T hT f => hS T hT (LTSHom.comp f h)

/-- **Transitivity axiom** for observation-class covering.
    Same self-probing trick: for any T_0 with C T_0 and g : T_0 -> G,
    g in S, then id in T.pullback g, giving g in T. -/
theorem labeled_obs_covering_transitive {L : Type} [Fintype L] [DecidableEq L]
    {C : LabeledObservationClass L} {G : FinLTS L} {S T : LTSSieve G}
    (hS : isLabeledObsCovering C G S)
    (hT : ∀ (H : FinLTS L) (f : LTSHom H G), S.mem H f →
      isLabeledObsCovering C H (T.pullback f)) :
    isLabeledObsCovering C G T := by
  intro T₀ hT₀ g
  have hg : S.mem T₀ g := hS T₀ hT₀ g
  have hTg : isLabeledObsCovering C T₀ (T.pullback g) := hT T₀ g hg
  have hid := hTg T₀ hT₀ (LTSHom.id T₀)
  simp only [LTSSieve.pullback] at hid
  rw [LTSHom.id_comp] at hid
  exact hid

/-!
## Part 10: Bracket Theorem
-/

/-- **Bracket upper bound:** bisim-covering implies C-covering for any C <= treeClass. -/
theorem labeled_spectrum_bracket_upper {L : Type} [Fintype L] [DecidableEq L]
    {C : LabeledObservationClass L}
    (h_tree : ∀ T, C T → labeledTreeClass T) {G : FinLTS L} {S : LTSSieve G}
    (hS : isLabeledBisimCovering G S) : isLabeledObsCovering C G S :=
  fun T hT f => hS T (h_tree T hT) f

/-- **Bracket lower bound:** C-covering implies trace-covering for any C >= pathClass. -/
theorem labeled_spectrum_bracket_lower {L : Type} [Fintype L] [DecidableEq L]
    {C : LabeledObservationClass L}
    (h_path : ∀ T, labeledPathClass T → C T) {G : FinLTS L} {S : LTSSieve G}
    (hS : isLabeledObsCovering C G S) : isLabeledTraceCovering G S := by
  intro w f
  have hpath : labeledPathClass (traceLTS w) := ⟨w, rfl⟩
  exact hS (traceLTS w) (h_path (traceLTS w) hpath) f

/-!
## Part 11: Strict Separation — fanLTS as Witness
-/

/-- fanLTS with a nonempty label list is a labeled rooted tree. -/
theorem fanLTS_isLabeledRootedTree {L : Type} [Fintype L] [DecidableEq L]
    (labels : List L) (_hlabels : 0 < labels.length) :
    LabeledIsRootedTree (fanLTS labels) := by
  refine ⟨⟨0, Nat.zero_lt_succ labels.length⟩, ?_, ?_, ?_⟩
  · -- no_edge_to_root: fanLTS edge from s to t requires s.val = 0 and
    -- t.val = i.val + 1 >= 1. If t = root (val 0), then 0 = i.val + 1, impossible.
    intro a v he
    obtain ⟨_, i, ht, _⟩ := he
    simp at ht
  · -- unique_parent: for v ≠ root, unique parent is ⟨0⟩
    intro v hne
    have hv_pos : 0 < v.val := by
      apply Nat.pos_of_ne_zero
      intro h; apply hne; exact Fin.ext h
    refine ⟨⟨0, Nat.zero_lt_succ labels.length⟩, ?_, ?_⟩
    · -- Existence: edge from 0 to v with label labels[v.val - 1]
      refine ⟨labels.get ⟨v.val - 1, by omega⟩, ?_⟩
      exact ⟨rfl, ⟨⟨v.val - 1, by omega⟩, by simp; omega, rfl⟩⟩
    · -- Uniqueness: if ∃ a, edge a p v then p.val = 0
      intro p ⟨_, hp, _⟩
      exact Fin.ext hp
  · -- all_reachable
    intro v
    by_cases hv : v.val = 0
    · have hv_eq : v = ⟨0, Nat.zero_lt_succ labels.length⟩ := Fin.ext hv
      rw [hv_eq]; exact LabeledReachable.refl _
    · have hv_pos : 0 < v.val := Nat.pos_of_ne_zero hv
      have hedge : (fanLTS labels).edge
          (labels.get ⟨v.val - 1, by omega⟩)
          ⟨0, Nat.zero_lt_succ labels.length⟩ v :=
        ⟨rfl, ⟨⟨v.val - 1, by omega⟩, by simp; omega, rfl⟩⟩
      exact LabeledReachable.step _ hedge (LabeledReachable.refl _)

/-- The identity on fanLTS [a, b] does NOT factor through any traceLTS w.

    Proof: if id = comp h f for h : fanLTS [a,b] -> traceLTS w and f : traceLTS w -> fanLTS [a,b],
    then h preserves edges. fanLTS [a,b] has edges (a, 0, 1) and (b, 0, 2).
    In traceLTS w, both would be edges from h(0). But traceLTS has at most one outgoing edge
    per vertex, with label w[h(0).val]. So w[h(0).val] = a and w[h(0).val] = b, giving a = b.
    But ThreeLabel.a != ThreeLabel.b. Contradiction. -/
theorem fanLTS_ab_id_not_in_traceGeneratedSieve :
    ¬(traceGeneratedSieve (fanLTS [ThreeLabel.a, ThreeLabel.b])).mem
      (fanLTS [ThreeLabel.a, ThreeLabel.b])
      (LTSHom.id (fanLTS [ThreeLabel.a, ThreeLabel.b])) := by
  intro ⟨w, h, f, heq⟩
  -- heq : id = comp h f, so for all v, f.toFun (h.toFun v) = v
  have hcomp : ∀ v, f.toFun (h.toFun v) = v := by
    intro v
    have heqf := congr_arg LTSHom.toFun heq
    exact (congr_fun heqf v).symm
  -- fanLTS [a, b] has edge (ThreeLabel.a, ⟨0,_⟩, ⟨1,_⟩)
  have hedge_a : (fanLTS [ThreeLabel.a, ThreeLabel.b]).edge ThreeLabel.a
      (⟨0, by show 0 < [ThreeLabel.a, ThreeLabel.b].length + 1; simp⟩)
      (⟨1, by show 1 < [ThreeLabel.a, ThreeLabel.b].length + 1; simp⟩) := by
    refine ⟨rfl, ⟨⟨0, by show 0 < [ThreeLabel.a, ThreeLabel.b].length; simp⟩, ?_, ?_⟩⟩
    · rfl
    · rfl
  -- fanLTS [a, b] has edge (ThreeLabel.b, ⟨0,_⟩, ⟨2,_⟩)
  have hedge_b : (fanLTS [ThreeLabel.a, ThreeLabel.b]).edge ThreeLabel.b
      (⟨0, by show 0 < [ThreeLabel.a, ThreeLabel.b].length + 1; simp⟩)
      (⟨2, by show 2 < [ThreeLabel.a, ThreeLabel.b].length + 1; simp⟩) := by
    refine ⟨rfl, ⟨⟨1, by show 1 < [ThreeLabel.a, ThreeLabel.b].length; simp⟩, ?_, ?_⟩⟩
    · rfl
    · rfl
  -- h preserves edge a: traceLTS w has edge (a, h(0), h(1))
  have h_edge_a := h.map_edge ThreeLabel.a _ _ hedge_a
  -- h preserves edge b: traceLTS w has edge (b, h(0), h(2))
  have h_edge_b := h.map_edge ThreeLabel.b _ _ hedge_b
  -- From traceLTS edge structure: w.get ⟨h(0).val, _⟩ = ThreeLabel.a
  -- and w.get ⟨h(0).val, _⟩ = ThreeLabel.b
  obtain ⟨h0_lt_a, hw_a, _⟩ := h_edge_a
  obtain ⟨h0_lt_b, hw_b, _⟩ := h_edge_b
  -- Both use h(0).val as the index, giving ThreeLabel.a = ThreeLabel.b
  have : ThreeLabel.a = ThreeLabel.b := by
    rw [← hw_a]
    have hfin_eq : (⟨(h.toFun ⟨0, by omega⟩).val, h0_lt_a⟩ : Fin w.length) =
           ⟨(h.toFun ⟨0, by omega⟩).val, h0_lt_b⟩ := by
      apply Fin.ext; rfl
    rw [hfin_eq]
    exact hw_b
  -- ThreeLabel.a != ThreeLabel.b by decide
  exact absurd this (by decide)

/-- fanLTS [ThreeLabel.a, ThreeLabel.b] is a labeled rooted tree. -/
theorem fanLTS_ab_isLabeledRootedTree :
    LabeledIsRootedTree (fanLTS [ThreeLabel.a, ThreeLabel.b]) :=
  fanLTS_isLabeledRootedTree [ThreeLabel.a, ThreeLabel.b] (by simp)

/-- The trace-generated sieve on fanLTS [a, b] is NOT bisim-covering. -/
theorem traceGeneratedSieve_not_bisimCovering_fanLTS_ab :
    ¬isLabeledBisimCovering (fanLTS [ThreeLabel.a, ThreeLabel.b])
      (traceGeneratedSieve (fanLTS [ThreeLabel.a, ThreeLabel.b])) := by
  intro hbc
  exact fanLTS_ab_id_not_in_traceGeneratedSieve
    (hbc (fanLTS [ThreeLabel.a, ThreeLabel.b])
      fanLTS_ab_isLabeledRootedTree
      (LTSHom.id (fanLTS [ThreeLabel.a, ThreeLabel.b])))

/-- **J_bisim is strictly finer than J_trace** for labeled LTS.

    Witness: traceGeneratedSieve on fanLTS [a,b] is trace-covering but not bisim-covering. -/
theorem labeled_bisim_strictly_finer_than_trace :
    ∃ (G : FinLTS ThreeLabel) (S : LTSSieve G),
      isLabeledTraceCovering G S ∧ ¬isLabeledBisimCovering G S :=
  ⟨fanLTS [ThreeLabel.a, ThreeLabel.b],
   traceGeneratedSieve (fanLTS [ThreeLabel.a, ThreeLabel.b]),
   traceGeneratedSieve_labeled_trace_covering (fanLTS [ThreeLabel.a, ThreeLabel.b]),
   traceGeneratedSieve_not_bisimCovering_fanLTS_ab⟩

/-!
## Part 12: Master Summary
-/

/-- Master theorem: labeled bisimulation topology with bracket theorem and strict separation.

    Combines:
    1. Three Grothendieck axioms for J_bisim (maximality, stability, transitivity)
    2. J_bisim finer than J_trace
    3. Non-bisimilarity of vgPairA and vgPairB (a.b+a.c NOT bisim a.(b+c))
    4. Bracket theorem: J_bisim <= J_C <= J_trace for observation classes C
    5. Strict separation: J_bisim strictly finer than J_trace -/
theorem labeled_bisim_bracket_summary {L : Type} [Fintype L] [DecidableEq L] :
    -- (1) Three Grothendieck axioms for J_bisim
    (∀ G : FinLTS L, isLabeledBisimCovering G (LTSSieve.maximal G)) ∧
    (∀ (G H : FinLTS L) (S : LTSSieve G) (h : LTSHom H G),
      isLabeledBisimCovering G S → isLabeledBisimCovering H (S.pullback h)) ∧
    (∀ (G : FinLTS L) (S T : LTSSieve G),
      isLabeledBisimCovering G S →
      (∀ (H : FinLTS L) (f : LTSHom H G), S.mem H f →
        isLabeledBisimCovering H (T.pullback f)) →
      isLabeledBisimCovering G T) ∧
    -- (2) J_bisim implies J_trace
    (∀ (G : FinLTS L) (S : LTSSieve G),
      isLabeledBisimCovering G S → isLabeledTraceCovering G S) ∧
    -- (3) Bracket: J_bisim <= J_C <= J_trace
    (∀ (C : LabeledObservationClass L),
      (∀ T, C T → labeledTreeClass T) →
      ∀ G S, isLabeledBisimCovering G S → isLabeledObsCovering C G S) ∧
    (∀ (C : LabeledObservationClass L),
      (∀ T, labeledPathClass T → C T) →
      ∀ G S, isLabeledObsCovering C G S → isLabeledTraceCovering G S) :=
  ⟨labeled_bisim_covering_maximal,
   fun _ _ _ h hS => labeled_bisim_covering_stable h hS,
   fun _ _ _ hS hT => labeled_bisim_covering_transitive hS hT,
   fun _ _ hS => labeledBisimCovering_implies_trace_covering hS,
   fun _ h_tree _ _ hS => labeled_spectrum_bracket_upper h_tree hS,
   fun _ h_path _ _ hS => labeled_spectrum_bracket_lower h_path hS⟩

end RTS.PresheafTopos
