/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.

# Labeled Trace Grothendieck Topology J_trace

This file defines the labeled trace Grothendieck topology on the category of finite
L-labeled transition systems (FinLTS L). A sieve S on G is labeled-trace-covering
iff it contains every homomorphism from every trace LTS (traceLTS w) into G, for
every word w : List L.

## Key Results

- `isLabeledTraceCovering`: the covering predicate for labeled J_trace
- Three Grothendieck axioms: maximality, stability, transitivity
- `labeled_trace_separation_iff`: trace equivalence iff same root-preserving hom sets
- `traceGeneratedSieve`: sieve generated by morphisms factoring through traceLTS
- `traceGeneratedSieve_labeled_trace_covering`: traceLTS density theorem

## Mathematical Significance

This is the labeled generalization of the trace topology from TraceTopology.lean.
The covering condition uses traceLTS w for words w over L as test objects, replacing
pathDigraph n (natural numbers) from the unlabeled setting. The path-hom bijection
from LabeledLTS.lean (trace_implies_hom / homToTrace) provides the bridge between
set-theoretic traces and categorical hom-sets.

## References

- Mac Lane & Moerdijk, "Sheaves in Geometry and Logic" (1992), III.2
- van Glabbeek, "The linear time--branching time spectrum I" (1990)
-/

import RuleSys.PresheafTopos.LabeledLTS

set_option autoImplicit false

namespace RTS.PresheafTopos

/-!
## Part 1: The Labeled Trace Covering Predicate
-/

/-- A sieve S on G is **labeled-trace-covering** if it contains every homomorphism
    from every trace LTS (traceLTS w) into G, for every word w : List L.

    This is the covering condition for the labeled trace topology J_trace.
    Intuitively: S "sees" all possible labeled traces through G -- for every word w
    and every way to trace w through G, that tracing is in S. -/
def isLabeledTraceCovering {L : Type} [Fintype L] [DecidableEq L]
    (G : FinLTS L) (S : LTSSieve G) : Prop :=
  ∀ (w : List L) (f : LTSHom (traceLTS w) G), S.mem (traceLTS w) f

/-!
## Part 2: Grothendieck Topology Axioms
-/

/-- **Maximality axiom:** The maximal sieve is labeled-trace-covering for every G.
    Every morphism into G is in the maximal sieve, so in particular all trace morphisms. -/
theorem labeled_trace_covering_maximal {L : Type} [Fintype L] [DecidableEq L]
    (G : FinLTS L) :
    isLabeledTraceCovering G (LTSSieve.maximal G) :=
  fun _ _ => trivial

/-- **Stability axiom:** If S labeled-trace-covers G, then the pullback f*(S)
    labeled-trace-covers H. Any trace morphism g : traceLTS w -> H becomes
    f . g : traceLTS w -> G, which is in S. -/
theorem labeled_trace_covering_stable {L : Type} [Fintype L] [DecidableEq L]
    {G H : FinLTS L} {S : LTSSieve G}
    (h : LTSHom H G) (hS : isLabeledTraceCovering G S) :
    isLabeledTraceCovering H (S.pullback h) :=
  fun w f => hS w (LTSHom.comp f h)

/-- **Transitivity axiom:** If S labeled-trace-covers G and for every (H, f) in S
    the pullback f*(T) labeled-trace-covers H, then T labeled-trace-covers G.

    Key insight (self-probing trick): for any trace morphism g : traceLTS w -> G,
    since S labeled-trace-covers G, g is in S. The hypothesis then gives:
    (T.pullback g) labeled-trace-covers traceLTS w. In particular, id_{traceLTS w}
    must be in T.pullback g, which means T.mem (traceLTS w) (comp id g) = T.mem _ g.
    Hence g is in T. -/
theorem labeled_trace_covering_transitive {L : Type} [Fintype L] [DecidableEq L]
    {G : FinLTS L} {S T : LTSSieve G}
    (hS : isLabeledTraceCovering G S)
    (hT : ∀ (H : FinLTS L) (f : LTSHom H G), S.mem H f →
      isLabeledTraceCovering H (T.pullback f)) :
    isLabeledTraceCovering G T := by
  intro w g
  -- g : traceLTS w -> G. Since S labeled-trace-covers G, g in S.
  have hg : S.mem (traceLTS w) g := hS w g
  -- By hypothesis, T.pullback g labeled-trace-covers traceLTS w.
  have hTg : isLabeledTraceCovering (traceLTS w) (T.pullback g) := hT (traceLTS w) g hg
  -- In particular, id_{traceLTS w} must be in T.pullback g.
  have hid := hTg w (LTSHom.id (traceLTS w))
  -- (T.pullback g).mem (traceLTS w) (id) = T.mem (traceLTS w) (comp id g) = T.mem _ g
  simp only [LTSSieve.pullback] at hid
  rw [LTSHom.id_comp] at hid
  exact hid

/-!
## Part 3: Summary
-/

/-- Master theorem: the labeled trace topology J_trace satisfies all three Grothendieck
    axioms -- maximality, stability, and transitivity. This establishes J_trace as
    a genuine Grothendieck topology on the category of finite L-labeled transition
    systems. -/
theorem labeled_trace_topology_summary {L : Type} [Fintype L] [DecidableEq L] :
    -- (1) Maximality
    (∀ G : FinLTS L, isLabeledTraceCovering G (LTSSieve.maximal G)) ∧
    -- (2) Stability
    (∀ (G H : FinLTS L) (S : LTSSieve G) (h : LTSHom H G),
      isLabeledTraceCovering G S → isLabeledTraceCovering H (S.pullback h)) ∧
    -- (3) Transitivity
    (∀ (G : FinLTS L) (S T : LTSSieve G),
      isLabeledTraceCovering G S →
      (∀ (H : FinLTS L) (f : LTSHom H G), S.mem H f →
        isLabeledTraceCovering H (T.pullback f)) →
      isLabeledTraceCovering G T) :=
  ⟨labeled_trace_covering_maximal,
   fun _ _ _ h hS => labeled_trace_covering_stable h hS,
   fun _ _ _ hS hT => labeled_trace_covering_transitive hS hT⟩

/-!
## Part 4: The Trace Separation Theorem
-/

/-- The labeled trace separation theorem: two rooted L-LTS are trace-equivalent iff
    they admit the same root-preserving homomorphisms from all trace LTS (traceLTS t).

    This is the categorical reformulation of labeled trace equivalence in terms of hom-sets:
    labeledTraceEquiv G v H w iff for all t : List L,
      Hom_v(traceLTS t, G) nonempty iff Hom_w(traceLTS t, H) nonempty

    where Hom_v(traceLTS t, G) = {f : traceLTS t -> G | f(0) = v}. -/
theorem labeled_trace_separation_iff {L : Type} [Fintype L] [DecidableEq L]
    {G : FinLTS L} {v : G.Vertex} {H : FinLTS L} {w : H.Vertex} :
    labeledTraceEquiv G v H w ↔
    ∀ (t : List L),
      (∃ f : LTSHom (traceLTS t) G, f.toFun ⟨0, Nat.zero_lt_succ t.length⟩ = v) ↔
      (∃ f : LTSHom (traceLTS t) H, f.toFun ⟨0, Nat.zero_lt_succ t.length⟩ = w) := by
  constructor
  · -- Forward: labeledTraceEquiv -> same hom sets
    intro heq t
    constructor
    · -- G side -> H side
      rintro ⟨f, hroot⟩
      have hp := homToTrace f
      rw [hroot] at hp
      -- hp : hasTrace G v t
      have hp' : hasTrace H w t := by
        rw [show hasTrace H w t ↔ t ∈ labeledTraceSet H w from Iff.rfl]
        rw [← heq]
        exact hp
      exact trace_implies_hom hp'
    · -- H side -> G side
      rintro ⟨f, hroot⟩
      have hp := homToTrace f
      rw [hroot] at hp
      have hp' : hasTrace G v t := by
        rw [show hasTrace G v t ↔ t ∈ labeledTraceSet G v from Iff.rfl]
        rw [heq]
        exact hp
      exact trace_implies_hom hp'
  · -- Backward: same hom sets -> labeledTraceEquiv
    intro hall
    ext t
    simp only [labeledTraceSet, Set.mem_setOf_eq]
    constructor
    · -- hasTrace G v t -> hasTrace H w t
      intro hp
      obtain ⟨f, hroot⟩ := trace_implies_hom hp
      have ⟨g, groot⟩ := (hall t).mp ⟨f, hroot⟩
      have := homToTrace g
      rw [groot] at this
      exact this
    · -- hasTrace H w t -> hasTrace G v t
      intro hp
      obtain ⟨f, hroot⟩ := trace_implies_hom hp
      have ⟨g, groot⟩ := (hall t).mpr ⟨f, hroot⟩
      have := homToTrace g
      rw [groot] at this
      exact this

/-!
## Part 5: TraceLTS Density Under Labeled J_trace
-/

/-- The trace-generated sieve on G: contains all morphisms that factor through
    some trace LTS. This is the sieve generated by {traceLTS w -> G | all w, all homs}
    under precomposition closure.

    A morphism g : K -> G is in this sieve iff there exist w : List L, h : K -> traceLTS w,
    and f : traceLTS w -> G such that g = comp h f (diagrammatic order). -/
def traceGeneratedSieve {L : Type} [Fintype L] [DecidableEq L]
    (G : FinLTS L) : LTSSieve G where
  mem := fun K g => ∃ (w : List L) (h : LTSHom K (traceLTS w))
    (f : LTSHom (traceLTS w) G), g = LTSHom.comp h f
  precomp_closed := fun {_H K} g k ⟨w, h, f, heq⟩ => by
    -- g = comp h f, need: comp k g factors through traceLTS w
    -- comp k g = comp k (comp h f) = comp (comp k h) f
    exact ⟨w, LTSHom.comp k h, f, by rw [heq, LTSHom.comp_assoc]⟩

/-- The trace-generated sieve is labeled-trace-covering: it contains all trace morphisms.

    For any traceLTS t -> G, take w = t, h = id, f = the morphism itself.
    This is the **density condition**: trace LTS form a J_trace-dense subcategory.

    By the Comparison Lemma (Johnstone C2.2.3), this implies:
    Sh(FinLTS L, J_trace) is equivalent to Sh(TraceLTS, J_trace|_{TraceLTS})
    where TraceLTS is the full subcategory on {traceLTS w | w in L*}. -/
theorem traceGeneratedSieve_labeled_trace_covering {L : Type} [Fintype L] [DecidableEq L]
    (G : FinLTS L) :
    isLabeledTraceCovering G (traceGeneratedSieve G) := by
  intro w f
  -- f : traceLTS w -> G. Factor as id . f: take h = id, f = f.
  exact ⟨w, LTSHom.id (traceLTS w), f, by rw [LTSHom.id_comp]⟩

/-!
## Part 6: Density Summary
-/

/-- Master theorem: labeled trace separation and density. -/
theorem labeled_trace_density_summary {L : Type} [Fintype L] [DecidableEq L] :
    -- (1) Trace separation: labeledTraceEquiv iff same root-preserving hom sets
    (∀ (G : FinLTS L) (v : G.Vertex) (H : FinLTS L) (w : H.Vertex),
      labeledTraceEquiv G v H w ↔
      ∀ t, (∃ f : LTSHom (traceLTS t) G,
              f.toFun ⟨0, Nat.zero_lt_succ t.length⟩ = v) ↔
           (∃ f : LTSHom (traceLTS t) H,
              f.toFun ⟨0, Nat.zero_lt_succ t.length⟩ = w)) ∧
    -- (2) TraceLTS density: trace-generated sieve is J_trace-covering
    (∀ G : FinLTS L, isLabeledTraceCovering G (traceGeneratedSieve G)) :=
  ⟨fun _ _ _ _ => labeled_trace_separation_iff, traceGeneratedSieve_labeled_trace_covering⟩

end RTS.PresheafTopos
