/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.

# Trace Separation and PathDigraph Density

This file proves the trace separation theorem: two rooted digraphs are trace-equivalent
iff they admit the same root-preserving homomorphisms from path digraphs P_n. This connects
the set-theoretic definition of trace equivalence to the categorical language of hom-sets.

## Key Results

- `trace_separation_iff`: traceEquiv ↔ same root-preserving hom sets from P_n
- `pathGeneratedSieve`: sieve on G generated by closing path morphisms under precomposition
- `pathGeneratedSieve_trace_covering`: path digraphs are J_trace-dense
- Concrete separations: P_1 separates •₀ from •₁ and from →(false); P_2 separates →(false) from •₁

## Mathematical Significance

The trace separation theorem is the bridge between the combinatorial (trace set) and
categorical (Grothendieck topology) perspectives. It implies the Comparison Lemma:
  Sh(FinDigraph, J_trace) ≃ Sh(PathDigraph, J_trace|_{PathDigraph})
where PathDigraph is the full subcategory on {P_n | n ∈ ℕ} ≅ (ℕ, ≤)^op.

For |L| = 1, this gives: the trace-equivalence sheaf topos is equivalent to presheaves
on the path category, which is a category of "shape probes" for traces.

## References

- Johnstone, "Sketches of an Elephant" (2002), C2.2.3 (Comparison Lemma)
- Joyal-Nielsen-Winskel, "Bisimulation from open maps" (1996)
-/

import RuleSys.PresheafTopos.TraceTopology

set_option autoImplicit false

namespace Ruliology.PresheafTopos

/-!
## Part 1: The Trace Separation Theorem
-/

/-- The trace separation theorem: two rooted digraphs are trace-equivalent iff they
    admit the same root-preserving homomorphisms from all path digraphs P_n.

    This is the categorical reformulation of trace equivalence in terms of hom-sets:
    traceEquiv G v H w ↔ ∀ n, Hom_v(P_n, G) ≠ ∅ ↔ Hom_w(P_n, H) ≠ ∅

    where Hom_v(P_n, G) = {f : P_n → G | f(0) = v}. -/
theorem trace_separation_iff {G : FinDigraph} {v : G.Vertex}
    {H : FinDigraph} {w : H.Vertex} :
    traceEquiv G v H w ↔
    ∀ n, (∃ f : DigraphHom (pathDigraph n) G, f.toFun ⟨0, Nat.zero_lt_succ n⟩ = v) ↔
         (∃ f : DigraphHom (pathDigraph n) H, f.toFun ⟨0, Nat.zero_lt_succ n⟩ = w) := by
  constructor
  · -- Forward: traceEquiv → same hom sets
    intro heq n
    constructor
    · -- G side → H side
      rintro ⟨f, hroot⟩
      have hp := homToPath f
      rw [hroot] at hp
      -- hp : hasPathOfLength G v n
      have hp' : hasPathOfLength H w n := by
        rw [show hasPathOfLength H w n ↔ n ∈ traceSet H w from Iff.rfl]
        rw [← heq]
        exact hp
      exact path_implies_hom hp'
    · -- H side → G side
      rintro ⟨f, hroot⟩
      have hp := homToPath f
      rw [hroot] at hp
      have hp' : hasPathOfLength G v n := by
        rw [show hasPathOfLength G v n ↔ n ∈ traceSet G v from Iff.rfl]
        rw [heq]
        exact hp
      exact path_implies_hom hp'
  · -- Backward: same hom sets → traceEquiv
    intro hall
    ext n
    simp only [traceSet, Set.mem_setOf_eq]
    constructor
    · -- hasPathOfLength G v n → hasPathOfLength H w n
      intro hp
      obtain ⟨f, hroot⟩ := path_implies_hom hp
      have ⟨g, groot⟩ := (hall n).mp ⟨f, hroot⟩
      have := homToPath g
      rw [groot] at this
      exact this
    · -- hasPathOfLength H w n → hasPathOfLength G v n
      intro hp
      obtain ⟨f, hroot⟩ := path_implies_hom hp
      have ⟨g, groot⟩ := (hall n).mpr ⟨f, hroot⟩
      have := homToPath g
      rw [groot] at this
      exact this

/-!
## Part 2: PathDigraph Density Under J_trace
-/

/-- The path-generated sieve on G: contains all morphisms that factor through
    some path digraph. This is the sieve generated by {P_n → G | all n, all homs}
    under precomposition closure.

    A morphism g : K → G is in this sieve iff there exist n, h : K → P_n, and
    f : P_n → G such that g = f ∘ h (in standard notation) = comp h f (diagrammatic). -/
def pathGeneratedSieve (G : FinDigraph) : DigraphSieve G where
  mem := fun K g => ∃ (n : ℕ) (h : DigraphHom K (pathDigraph n))
    (f : DigraphHom (pathDigraph n) G), g = DigraphHom.comp h f
  precomp_closed := fun {_H K} g k ⟨n, h, f, heq⟩ => by
    -- g = comp h f, need: comp k g factors through P_n
    -- comp k g = comp k (comp h f) = comp (comp k h) f
    exact ⟨n, DigraphHom.comp k h, f, by rw [heq, DigraphHom.comp_assoc]⟩

/-- The path-generated sieve is trace-covering: it contains all path morphisms.

    For any P_m → G, take n = m, h = id, f = the morphism itself.
    This is the **density condition**: path digraphs form a J_trace-dense subcategory.

    By the Comparison Lemma (Johnstone C2.2.3), this implies:
    Sh(FinDigraph, J_trace) ≃ Sh(PathDigraph, J_trace|_{PathDigraph}) -/
theorem pathGeneratedSieve_trace_covering (G : FinDigraph) :
    isTraceCovering G (pathGeneratedSieve G) := by
  intro n f
  -- f : P_n → G. Factor as id ∘ f: take h = id, f = f.
  exact ⟨n, DigraphHom.id (pathDigraph n), f, by rw [DigraphHom.id_comp]⟩

/-!
## Part 3: Concrete Separations

Path digraphs as "test objects" that separate non-trace-equivalent digraphs.
-/

/-- P_1 separates •₀ from •₁: there is a root-preserving hom P_1 → •₁
    but no root-preserving hom P_1 → •₀. -/
theorem path_one_separates_noloop_loop :
    (∃ f : DigraphHom (pathDigraph 1) loopVertex,
      f.toFun ⟨0, Nat.zero_lt_succ 1⟩ = ()) ∧
    ¬(∃ f : DigraphHom (pathDigraph 1) looplessVertex,
      f.toFun ⟨0, Nat.zero_lt_succ 1⟩ = ()) := by
  constructor
  · -- •₁ has paths of all lengths
    exact path_implies_hom (loopVertex_hasPath_all 1)
  · -- •₀ has no path of length 1
    rintro ⟨f, _⟩
    exact looplessVertex_no_longer_path 0 (homToPath f)

/-- P_1 separates •₀ from →(false): there is a root-preserving hom P_1 → →
    sending 0 to false, but no root-preserving hom P_1 → •₀. -/
theorem path_one_separates_noloop_arrow :
    (∃ f : DigraphHom (pathDigraph 1) arrowDigraph,
      f.toFun ⟨0, Nat.zero_lt_succ 1⟩ = false) ∧
    ¬(∃ f : DigraphHom (pathDigraph 1) looplessVertex,
      f.toFun ⟨0, Nat.zero_lt_succ 1⟩ = ()) := by
  constructor
  · exact path_implies_hom arrow_hasPath_false_one
  · rintro ⟨f, _⟩
    exact looplessVertex_no_longer_path 0 (homToPath f)

/-- P_2 separates →(false) from •₁: there is a root-preserving hom P_2 → •₁
    but no root-preserving hom P_2 → → sending 0 to false.
    This witnesses that •₁ has longer traces than the arrow graph. -/
theorem path_two_separates_arrow_loop :
    (∃ f : DigraphHom (pathDigraph 2) loopVertex,
      f.toFun ⟨0, Nat.zero_lt_succ 2⟩ = ()) ∧
    ¬(∃ f : DigraphHom (pathDigraph 2) arrowDigraph,
      f.toFun ⟨0, Nat.zero_lt_succ 2⟩ = false) := by
  constructor
  · exact path_implies_hom (loopVertex_hasPath_all 2)
  · rintro ⟨f, hroot⟩
    have := homToPath f
    rw [hroot] at this
    exact arrow_no_path_false_ge2 0 this

/-!
## Part 4: Summary

The trace separation theorem and path density establish the fundamental bridge
between the combinatorial (trace sets) and categorical (Grothendieck topology)
perspectives on trace equivalence.

**Separation hierarchy:**
- P_1 separates {•₀, →(true)} from {•₁, →(false)}: presence of length-1 traces
- P_2 separates →(false) from •₁: the arrow has bounded traces, the loop doesn't

**Density:** The full subcategory PathDigraph = {P_n | n ∈ ℕ} is J_trace-dense in FinDigraph.
By the Comparison Lemma (Johnstone C2.2.3):
  Sh(FinDigraph, J_trace) ≃ Sh(PathDigraph, J_trace|_{PathDigraph})

For |L| = 1, PathDigraph ≅ (ℕ, ≤)^op via the inclusions P_n ↪ P_{n+1} (Phase 164).
So the trace-equivalence sheaf topos is equivalent to (generalized) presheaves on (ℕ, ≤).
-/

/-- Master theorem: trace separation and density. -/
theorem trace_density_summary :
    -- (1) Trace separation: traceEquiv ↔ same root-preserving hom sets
    (∀ (G : FinDigraph) (v : G.Vertex) (H : FinDigraph) (w : H.Vertex),
      traceEquiv G v H w ↔
      ∀ n, (∃ f : DigraphHom (pathDigraph n) G, f.toFun ⟨0, Nat.zero_lt_succ n⟩ = v) ↔
           (∃ f : DigraphHom (pathDigraph n) H, f.toFun ⟨0, Nat.zero_lt_succ n⟩ = w)) ∧
    -- (2) PathDigraph density: path-generated sieve is J_trace-covering
    (∀ G : FinDigraph, isTraceCovering G (pathGeneratedSieve G)) :=
  ⟨fun _ _ _ _ => trace_separation_iff, pathGeneratedSieve_trace_covering⟩

end Ruliology.PresheafTopos
